### ISSUE TITLE
Can't ./nova.sh run more than once

### ISSUE THREAD

**Issue by littleidea** [vishvananda/novascript#2]
it fails of you stop and try to run again:

The big culprits so far:

redis:
 /home/vagrant/novascript/redis-2.0.0-rc4/redis-server
[16974] 24 Sep 20:20:32 # Warning: no config file specified, using the default config. In order to specify a config file use 'redis-server /path/to/redis.conf'
[16974] 24 Sep 20:20:32 # Opening TCP port: bind: Address already in use

nova-network:
sqlalchemy.exc.OperationalError: (OperationalError) table auth_tokens already exists u'\nCREATE TABLE auth_tokens (\n\tcreated_at DATETIME, \n\tupdated_at DATETIME, \n\tdeleted_at DATETIME, \n\tdeleted BOOLEAN, \n\ttoken_hash VARCHAR(255) NOT NULL, \n\tuser_id INTEGER, \n\tserver_manageent_url VARCHAR(255), \n\tstorage_url VARCHAR(255), \n\tcdn_management_url VARCHAR(255), \n\tPRIMARY KEY (token_hash), \n\tCHECK (deleted IN (0, 1))\n)\n\n' ()

nova-manage:
nova.exception.Duplicate: Project can't be created because project admin already exists

Either need to clean up better on exit or startup.

Or make everything idempotent.

I'll eventually get this into configuration management, once nova stabilizes a bit and I understand how to install everything.

(This helped a lot, so thanks)

**Comment by vishvananda** [comment]
If you disconnect from screen, it 'should' clean up everything automatically, but if the build is messed up it may not.  I added some commentary to the readme and added a few commands to help clean things up if you get stuck.

**Comment by vishvananda** [comment]
think this is ok now that the claen command is in.
