### ISSUE TITLE
Run fails

### ISSUE THREAD

**Issue by antani** [vishvananda/novascript#7]
I am on Ubuntu Natty. 
when I try to run : sudo ./nova.sh run I keep getting :
2011-05-11 14:45:44,771 CRITICAL nova [-](OperationalError) (1045, "Access denied for user 'root'@'localhost' (using password: YES)") None None

I tried manually syncing the DB also : 
ved@ved-ubuntu:~/nova/nova/bin$ sudo ./nova-manage db sync
fails with the same error :
2011-05-11 14:45:44,771 CRITICAL nova [-](OperationalError) (1045, "Access denied for user 'root'@'localhost' (using password: YES)") None None

**Comment by vishvananda** [comment]
interesting.  Is it possible you set up mysql with another password?  The script tries to set up a mysql root password for you, but if you already have one it probably won't work.

**Comment by antani** [comment]
Yes I have root user with "password" password setup. Do I need to change that ? what is the password NOVA run script tries to set ? perhaps I will try setting the password manually

**Comment by vishvananda** [comment]
You can edit the password in the nova.sh file.  by default it uses nova, but it is an env variable, so:
sudo MYSQL_PASS=password ./nova.sh run
or you can edit line 24
